---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      containers:
      - image: nginx:1.9.12
        name: nginx
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf
        command:
        - '/usr/sbin/nginx'
        - '-c'
        - '/etc/nginx/conf/nginx.conf'
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
        # Other service ports...
