---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  - name: murmur
    port: 64737
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-udp
#   labels:
#     app: nginx
# spec:
#   type: LoadBalancer
#   selector:
#     app: nginx
#   ports:
#     - name: murmur
#       port: 64737
#       protocol: UDP
# Does NOT allow us to bind a different LB to the same port, despite it
# being a different protocol. I can't find documentation as to why,
# and a LB can't have both TCP/UDP bound at once, so ... yay!
