---
apiVersion: v1
kind: Service
metadata:
  name: murmur
  labels:
    app: murmur
spec:
  type: NodePort
  selector:
    app: murmur
  ports:
  - name: control
    protocol: TCP
    port: 64738
    targetPort: 64738
    nodePort: 32581
  - name: voice
    protocol: UDP
    port: 64738
    targetPort: 64738
    nodePort: 32581
  - name: ice
    protocol: TCP
    port: 6502
    targetPort: 6502
    nodePort: 32700
  - name: sybot-api
    protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 32701
    # setting nodePort to the standards would be nice,
    # but the default install restricts us to 30000+.
    # Will see about an nginx proxy (with UDP proxying?)
    # as an alternative... Otherwise may need to stick
    # some additional iptables routing rules on the host
    # to forward a standard service port.
